import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        {/* <meta
          name="google-site-verification"
          content="LAFLPJO73XDxXz1ZA7Oa8g_g3xdfcL24i9sEhlt9G6o"
        /> */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/accordion/htmlTag">With Html Tags</Link>
      <Link href="/accordion/conditionalRendering">
        With Conditional Rendering
      </Link>
    </>
  );
}
